services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: "Europe/Madrid"           # Cambia tu zona horaria
      WEBPASSWORD: "erossensey23" # Contrase√±a de acceso al panel
      DNS1: 1.1.1.1
      DNS2: 9.9.9.9
    volumes:
      - ./etc:/etc/pihole
      - ./dnsmasq:/etc/dnsmasq.d
    ports:
      - "8880:80/tcp"   # Panel web
      - "53:53/tcp"
      - "53:53/udp"
    restart: unless-stopped
    networks:
      - wg_pihole

networks:
  wg_pihole:
    external: true

